### ISSUE TITLE
Error on saving a user

### ISSUE THREAD

**Issue by nikcani** [TimonLukas/laravel-working-hours#10]
(3/3) ErrorException
Trying to get property of non-object (View: /resources/views/audit.blade.php) (View: /resources/views/audit.blade.php)

**Comment by TimonLukas** [comment]
Need steps to reproduce.

**Comment by nikcani** [comment]
when i click save on editing a user the error appears

**Comment by TimonLukas** [comment]
Still can't reproduce - I created a new user, saved it (associated with no projects), pressed edit, changed the hourly rate, and saved again. It got stored properly. Please try to reproduce it in a clean environment and describe all steps.
